# Generated by Django 3.0.2 on 2020-01-14 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_shopName', models.CharField(max_length=100)),
                ('customer_Pan', models.IntegerField()),
                ('customer_address', models.CharField(max_length=100)),
                ('customer_district', models.CharField(max_length=100)),
                ('customer_proporator', models.CharField(max_length=100)),
                ('customer_proporatorMobile', models.IntegerField()),
                ('customer_contactPerson', models.CharField(max_length=100)),
                ('customer_contactPersonMobile', models.IntegerField()),
                ('customer_shopNumber', models.IntegerField()),
                ('customer_residentPhone', models.IntegerField()),
                ('customer_Transportation', models.CharField(max_length=100)),
                ('customer_username', models.CharField(max_length=20)),
                ('customer_email', models.EmailField(max_length=150)),
                ('password', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=100)),
                ('product_image', models.ImageField(default='', upload_to='shop/images')),
                ('product_category', models.CharField(max_length=50)),
                ('unit_Of_Product', models.CharField(max_length=25)),
                ('product_rate', models.DecimalField(decimal_places=4, max_digits=50)),
                ('product_details', models.TextField()),
            ],
        ),
    ]
