# Generated by Django 3.0.2 on 2020-01-25 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20200122_1159'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='customer_Username',
            new_name='username',
        ),
    ]
