# Generated by Django 3.0.2 on 2020-02-06 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20200125_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='customer_shopPic',
            field=models.ImageField(default='', upload_to='shop/images'),
        ),
    ]
