# Generated by Django 3.0.2 on 2020-02-06 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20200206_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_shopPic',
            field=models.ImageField(default='', upload_to='shop/images/shop picture'),
        ),
    ]
